version: "3.8"

services:
  web:
    container_name: mern-template
    ports:
      - 5000:5000
      - 3000:3000
    environment:
      - MONGO_URI=mongodb://db:27017/test
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mongo:4.2-bionic
    ports:
      - 27017:27017
